apiVersion: v2
name: traefik
version: 1.0.2
description: This Chart deploys traefik.
dependencies:
  - name: traefik
    version: 39.0.0
    repository: oci://ghcr.io/traefik/helm
  - name: template-library
    repository: file://../template-library
    version: 0.0.9
