apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    labels:
        argocd.argoproj.io/instance: {{ .cluster.name }}-external-secrets
    name: "{{ .cluster.name }}-{{ .cluster.stage }}"
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: external-secrets
        type: Secret
      identityURL: https://vault.bitwarden.com/identity
      organizationID: b1175f2a-4359-4fb0-a495-b41600da0782
      projectID: 6bb7bae4-0fcc-4579-86cf-b41600dab145

