clusterIssuer:
  name: letsencrypt-staging
  email: yourname@your-domain.de
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  ingressClassName: traefik


cert-manager:
  prometheus:
    servicemonitor:
      labels:
        monitoring.instance: controlplane-prod

namespace:
  labels:
    project-name: "controlplane"
    stage: "prod"
