apiVersion: v2
name: vcluster
version: 1.0.2
description: This Chart deploys vcluster k3s by default.
dependencies:
  - name: vcluster
    version: 0.31.0
    repository: https://charts.loft.sh
  - name: template-library
    repository: file://../template-library
    version: 0.0.9
