namespace: {}
oauth2-proxy:
  metrics:
    serviceMonitor:
      enabled: false
      labels:
        monitoring.instance: change-me
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
