namespace:
  labels:
    project-name: "controlplane"
    stage: "prod"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
poolName: first-pool
addresses:
  - <no value>/32

metallb:
  prometheus:
    serviceMonitor:
      speaker:
        additionalLabels:
          monitoring.instance: "controlplane-prod"
      controller:
        additionalLabels:
          monitoring.instance: "controlplane-prod"
