kube-prometheus-stack:
  global:
    imageRegistry: ""
  prometheusOperator:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
    prometheus:
      monitor:
        additionalLabels:
          monitoring.instance: controlplane-prod
  prometheus:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
    ingress:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      paths:
        - /prometheus
      pathType: ImplementationSpecific
      hosts:
        - controlplane-prod.172.18.255.254.traefik.me
      tls:
        - secretName: tls-prometheus
          hosts:
            - controlplane-prod.172.18.255.254.traefik.me


    prometheusSpec:
      retention: 10d
      serviceMonitorSelector:
        matchLabels:
          monitoring.instance: controlplane-prod
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      externalUrl: https://controlplane-prod.172.18.255.254.traefik.me/prometheus
      routePrefix: /prometheus
    thanosServiceMonitor:
      serviceMonitor:
        additionalLabels:
          monitoring.instance: controlplane-prod
  alertmanager:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
    ingress:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      paths:
        - /alertmanager
      pathType: ImplementationSpecific
      hosts:
        - controlplane-prod.172.18.255.254.traefik.me
      tls:
        - secretName: tls-alertmanager
          hosts:
            - controlplane-prod.172.18.255.254.traefik.me


# Below is an example alertmanager.config section:
# It demonstrates an advanced routing setup that includes Microsoft Teams (v2), a watchdog receiver
# (e.g. for UptimeRobot) and a silenced route for informational alerts.
# This config use webhook urls from secret-files (see alertmanagerSpec below)
#
#    config:
#      route:
#        receiver: msteams-notifications  # Default receiver if no route matches
#        routes:
#          # 1. Silence all alerts named "InfoInhibitor"
#          - receiver: "null"
#            matchers:
#              - alertname =~ "InfoInhibitor"
#          # 2. Route "Watchdog" alerts to UptimeRobot with a short repeat interval
#          - receiver: uptimerobot
#            repeat_interval: 1m
#            matchers:
#              - alertname =~ "Watchdog"
#          # 3. Route all alerts with severity "warning" or "critical" to Microsoft Teams
#          - receiver: 'msteams-notifications'
#            matchers:
#              - severity =~ "warning|critical"
#            continue: true  # Continue to evaluate other routes after this one
#      receivers:
#        # Microsoft Teams v2 receiver using `msteamsv2_configs`
#        - name: 'msteams-notifications'
#          msteamsv2_configs:
#            - send_resolved: true
#              webhook_url_file: /etc/alertmanager/secrets/msteams-webhook-url
#        # Watchdog/Uptime monitoring receiver
#        - name: uptimerobot
#          webhook_configs:
#            - url_file: /etc/alertmanager/secrets/uptimerobot-webhook-url
#        # Null receiver to discard matched alerts
#        - name: "null"
#      # Optional: Use custom templates for consistent alert formatting
#      templates:
#        - /etc/alertmanager/config/*.tmpl

    alertmanagerSpec:
#      # secrets for alertmanager config webhook urls
#      secrets:
#        - msteams-webhook-url
#        - uptimerobot-webhook-url
      externalUrl: https://controlplane-prod.172.18.255.254.traefik.me/alertmanager
      routePrefix: /alertmanager

  kube-state-metrics:
    prometheus:
      monitor:
        additionalLabels:
          monitoring.instance: controlplane-prod
  kubeApiServer:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  kubelet:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  kubeControllerManager:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  coreDns:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  kubeDns:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  kubeScheduler:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  thanosRuler:
    serviceMonitor:
      additionalLabels:
        monitoring.instance: controlplane-prod
  grafana:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    serviceMonitor:
      labels:
        monitoring.instance: controlplane-prod
    ingress:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      path: /grafana
      pathType: ImplementationSpecific
      hosts:
        - controlplane-prod.172.18.255.254.traefik.me
      tls:
        - secretName: tls-grafana
          hosts:
            - controlplane-prod.172.18.255.254.traefik.me
    envFromSecrets:
      - name: oauth2-credentials
    grafana.ini:
      server:
        root_url: https://controlplane-prod.172.18.255.254.traefik.me/grafana/
        serve_from_sub_path: true
    additionalDataSources:
      - access: proxy
        isDefault: false
        name: loki
        type: loki
        url: http://loki-headless.loki.svc.cluster.local:3100
        version: 1
prometheus-blackbox-exporter:
  global:
    imageRegistry: quay.io

externalSecrets:
  secretStoreRef:
    kind: ClusterSecretStore
    name: controlplane-prod

  secretStores:
    controlplane-prod:
      kind: ClusterSecretStore
      name: controlplane-prod

  secrets:
    grafana-admin-credentials:
      secretStoreRef: controlplane-prod
      data:
        - remoteKey: controlplane-prod-grafana-admin-user
          remoteKeyProperty: admin-user
          secretKey: admin-user
        - remoteKey: controlplane-prod-grafana-admin-password
          remoteKeyProperty: admin-password
          secretKey: admin-password

namespace:
  labels:
    project-name: "controlplane"
    stage: "prod"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
